### ISSUE TITLE
a directory in a expanded parent directory is displayed duplicately

### ISSUE THREAD

**Issue by glassesneo** [Shougo/ddu.vim#113]
**Warning: I will close the issue without the minimal init.vim and the
reproduction instructions.**

# Problems summary
ディレクトリをexpand→その子ディレクトリに移動した後、`narrow({path = ".."})`すると同一の子ディレクトリが複数表示される

## Environment Information

- ddu.vim version (SHA1):
6143d179eddc05f57ed3ae0d3ca65f5871938896

- denops.vim version (SHA1):
9dd9ae9da9b8d65916dd44e0e4d881665397de63

- deno version(`deno -V` output):
deno 1.43.5

- OS:
MacOS Sonoma 14.5 (M1, 2020)

- neovim/Vim `:version` output:
NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1713484068

## config

```lua
local doAction = vim.fn["ddu#ui#async_action"]

vim.fn["ddu#custom#patch_local"]("filer", {
  ui = "filer",
  uiParams = {
    filer = {
      splitDirection = "floating",
      floatingBorder = "rounded",
      previewFloating = true,
      previewFloatingBorder = "rounded",
      previewFloatingTitle = "Preview",
      previewSplit = "horizontal",
      split = "floating",
    },
  },
  sources = { "file" },
  sourceOptions = {
    file = {
      converters = {
        "converter_devicon",
      },
      columns = {
        "filename",
      },
    },
  },
})

---@param mode string|string[]
---@param key string
---@param action string
---@param args? table
local function mapAction(mode, key, action, args)
  vim.keymap.set(mode, key, function()
    if args ~= nil and next(args) then
      doAction(action, args)
    else
      doAction(action)
    end
  end, { noremap = true, silent = true, buffer = true })
end

vim.api.nvim_create_autocmd("FileType", {
  pattern = "ddu-filer",
  callback = function()
    mapAction("n", "q", "quit")
    mapAction("n", "<CR>", "itemAction", { name = "narrow"})
    mapAction("n", "<BS>", "itemAction", { name = "narrow", params = { path = ".." } })
    mapAction("n", "o", "expandItem", { mode = "toggle" })
  end,

```

## How to reproduce the problem from neovim/Vim startup (Required!)

1. `:call ddu#start(#{name:"filer"})`や`:Ddu -name=filer`などでdduをスタート
2. 任意のディレクトリをexpandし、その中のディレクトリを選択してnarrow
3. narrow(path = "..")で最初にexpandしたディレクトリに戻る

## Screenshot

https://github.com/Shougo/ddu.vim/assets/61031352/b0c36b89-87c9-4aa8-b6b8-f2b093334921

動画内のディレクトリ構造
```
.
├── elm
│   ├── Main.elm
│   └── elmDir
│       └── sub.elm
├── lua
│   ├── luaDir
│   │   └── sub.lua
│   └── main.lua
└── nim
    ├── main.nim
    └── nimDir
        └── sub.nim
```

**Comment by Shougo** [comment]
Fixed.
