### ISSUE TITLE
Fail to call patch_global when `-V1` given in CLI arguments

### ISSUE THREAD

**Issue by kyoh86** [Shougo/ddu.vim#115]
**Warning: I will close the issue without the minimal init.vim and the
reproduction instructions.**

# Problems summary

When I use Neovim with `-V[N]` options over `N >= 1`, `ddu#custom#global_patch` definitely fails with following error.

```
Error detected while processing function ddu#custom#patch_global[2]..<SNR>69_notify[7]..ddu#denops#_notify[1]..<SNR>70_init:
line   23:
E497: No autocommand match name to substitute for "<amatch>"
```

## Expected

Success to patch global config.

## Environment Information

- ddu.vim version (SHA1): `0ef167492f10642c0aa512f37febb1241517ade1`

- denops.vim version (SHA1): `9dd9ae9da9b8d65916dd44e0e4d881665397de63`

- deno version(`deno -V` output): `deno 1.44.1`

- OS: `Arch Linux`

- neovim/Vim `:version` output:

```
NVIM v0.11.0-dev-78d3f47
Build type: Release
LuaJIT 2.1.1716656478
Run ":verbose version" for more info
```

## Provide a minimal init.vim/vimrc without plugin managers (Required!)

```vim
set rtp+=/path/to/denops.vim
set rtp+=/path/to/ddu.vim
```

## How to reproduce the problem from neovim/Vim startup (Required!)

1. Start Neovim with `nvim -V1`
2. `:call ddu#custom#patch_global({})`

## Upload the log messages by `:redir` and `:message` (if errored)

```
Error detected while processing function ddu#custom#patch_global[2]..<SNR>69_notify[7]..ddu#denops#_notify[1]..<SNR>70_init:
line   23:
E497: No autocommand match name to substitute for "<amatch>"
```

**Comment by Shougo** [comment]
Fixed.
