### ISSUE TITLE
Filtering issues when using slow sources and entering match input

### ISSUE THREAD

**Issue by kyoh86** [Shougo/ddu.vim#130]
**Warning: I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary

When using a slowly populating source (items appear incrementally over time) in `ddu.vim`, filtering becomes unreliable if match input is attempted before all candidates have loaded. The entered filter text sometimes disappears and does not apply until after the source has fully populated.

## Expected

- Filtering should work reliably even while the source is still populating.  
- The entered match input should persist and filter results as items are added.

## Environment Information

- ddu.vim version (SHA1):  
  `3fa8a5aedbd3d2cb088aed014249220ee0b253e0`
- denops.vim version (SHA1):  
  `4ff8f353ee54ee67288c1099242444ccb0ab5b69`
- deno version(`deno -V` output):  
  ```  
  deno 2.1.4 (stable, release, x86_64-unknown-linux-gnu)
  v8 13.0.245.12-rusty
  typescript 5.6.2
  ```
- OS: `Ubuntu 24.04.1 LTS`
- neovim/Vim `:version` output:  
    ```
    NVIM v0.11.0-dev-f9dd682
    Build type: Release
    LuaJIT 2.1.1732813678
    Run ":verbose version" for more info
    ```

## Provide a minimal init.vim/vimrc without plugin managers (Required!)

```vim
set runtimepath+=/path/to/denops.vim/
set runtimepath+=/path/to/ddu.vim/
set runtimepath+=/path/to/ddu-ui-ff/
set runtimepath+=/path/to/ddu-filter-matcher_substring/

let g:denops#deno = $HOME .. "/.deno/bin/deno"
call ddu#custom#patch_global({
      \   "sources": [{
      \     "name": "slow",
      \     "options": {
      \       "matchers": [ "matcher_substring" ]
      \     }
      \   }],
      \   "ui": {
      \     "name": "ff"
      \   }
      \ })

" Key mappings for testing
nnoremap <leader>f <cmd>call ddu#start()<cr>
nnoremap <leader>m <cmd>call ddu#ui#do_action("openFilterWindow")<cr>
```

### slow.ts (source)

```typescript
import { BaseSource } from "jsr:@shougo/ddu-vim@~9.1.0/source";

type ActionData = Record<PropertyKey, never>;
type Params = Record<PropertyKey, never>;

export class Source extends BaseSource<Params, ActionData> {
  override gather() {
    return new ReadableStream({
      async start(controller) {
        const stack = [...Array(10).keys()];
        await new Promise((resolve) => {
          const timer = setInterval(() => {
            const x = stack.pop();
            if (x === undefined) {
              clearInterval(timer);
              resolve(undefined);
              return;
            }
            controller.enqueue([
              { word: `${x * 2 + 1}` },
              { word: `${x * 2}` },
            ]);
          }, 1000);
        }).finally(() => controller.close());
      },
    });
  }

  override params() {
    return {};
  }
}
```

## How to reproduce the problem from neovim/Vim startup (Required!)

1. Start neovim with the minimal config and ensure the `slow.ts` source is available in your runtime (`denops/@ddu-sources/slow.ts`).
2. Run `:call ddu#start()` (mapped as `\f` above) to start `ddu.vim`.
3. Observe as the `slow` source gradually adds candidates (2 items per second).
4. While items are still appearing (not all have loaded), open the match input window (`\m`).
5. Type `0<CR>` to try filtering the candidates.
   - Expected: The filter narrows down to candidates containing `0`.
   - Actual: No filtering occurs at this time.
6. Immediately press `\m` again to return to match input.
   - Observed: The previously typed `0` may have disappeared.
7. Retype `0<CR>` and attempt to filter again.
   - Result: Filtering still does not occur.
8. Wait until all candidates have loaded.
9. After the source finishes populating, filtering works as expected.

## Screenshot (if possible)

https://github.com/user-attachments/assets/f25b8e7e-436d-4dbd-ba0e-5d8b069ed69d

## Upload the log messages by `:redir` and `:message` (if errored)

*No explicit error messages were shown. No logs currently available.*

**Comment by Shougo** [comment]
Reproduced.

**Comment by Shougo** [comment]
I get the reason.

**Comment by Shougo** [comment]
Fixed.
