### ISSUE TITLE
Crash on `call ddu#start({})` by `E523: Not allowed here` in some case

### ISSUE THREAD

**Issue by lambdalisue** [Shougo/ddu.vim#14]
**Warning: I will close the issue without the minimal init.vim and the
reproduction instructions.**

# Problems summary

Invoking `call ddu#start({})` crashes denops.vim itself by `E523: Not allowed here` when statusline/tabline call function that invokes RPC call on Vim and Neovim (or `sleep` on Neovim.)

It seems `sbuffer` is called in statusline/tabline update context because of RPC asynchronous call and it seems that's not allowed. So I guess this is more likely a bug on Vim/Neovim side but not sure...

I wonder if `call ddu#start({})` wrap internal call with `timer_start()` to evacuate `sbuffer` from that context solves this issue or not.

## Expected

Works properly

## Environment Information

- ddu.vim version (SHA1): [b52e60b](https://github.com/Shougo/ddu.vim/commit/b52e60be5c538448a76ba94da7324ea5aef56992)

- denops.vim version (SHA1): [963a8a9](https://github.com/vim-denops/denops.vim/commit/963a8a9effd785e3ba6c6596aa265a9d85fe92ba)

- gin.vim (SHA1): [fe45b9e](https://github.com/lambdalisue/gin.vim/commit/fe45b9ecf067dff85d86026b2346fb67e3f10a02)
    - **NOTE**: [Workaround](https://github.com/lambdalisue/gin.vim/pull/41) for this issue is already applied so you MUST use this SHA1 to reproduce the issue

- deno version(`deno -V` output): `deno 1.20.3`

- OS: macOS 12.3

- neovim/Vim `:version` output:
    - Neovim v0.7.0-dev+1373-g80d4d6b48
    - Neovim v0.6.2
    - Vim 8.2.4600

- `:checkhealth` or `:CheckHealth` result(neovim only):

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
if exists('+compatible') && &compatible
  set nocompatible
endif

" Disable Vim's native pack feature
set packpath=

" Clone https://github.com/lambdalisue/fern.vim in somewhere
" and specify that directory to the below
set runtimepath^=~/.config/nvim/pack/jetpack/src/denops.vim
set runtimepath^=~/.config/nvim/pack/jetpack/src/gin.vim
set runtimepath^=~/.config/nvim/pack/jetpack/src/ddu.vim
set runtimepath^=~/.config/nvim/pack/jetpack/src/ddu-ui-ff
set runtimepath^=~/.config/nvim/pack/jetpack/src/ddu-kind-file
set runtimepath^=~/.config/nvim/pack/jetpack/src/ddu-source-file_rec
set runtimepath^=~/.config/nvim/pack/jetpack/src/ddu-filter-matcher_substring

filetype plugin indent on
syntax on
"----------------------------------------------------------------

nnoremap ; :
nnoremap : ;

call ddu#custom#patch_global({
    \   'ui': 'ff',
    \   'sources': [{'name': 'file_rec', 'params': {}}],
    \   'sourceOptions': {
    \     '_': {
    \       'matchers': ['matcher_substring'],
    \     },
    \   },
    \   'kindOptions': {
    \     'file': {
    \       'defaultAction': 'open',
    \     },
    \   }
    \ })

set showtabline=2
" Crash with RPC calls in Vim or Neovim
set tabline=%{gin#component#worktree#name()}
" Or crash with sleep in Neovim (Vim won't)
" set tabline=%{Sleep()}
function! Sleep() abort
  sleep 10m
  return "Hello"
endfunction

"----------------------------------------------------------------
echomsg "Custom minimal vimrc has loaded"
```

## How to reproduce the problem from neovim/Vim startup (Required!)

1. Invoke `:call ddu#start({})`

## Screenshot (if possible)

![CleanShot 2022-04-01 at 08 08 11](https://user-images.githubusercontent.com/546312/161164015-8563b9da-9ac5-448a-8b51-c2f07761500b.png)

**Comment by Shougo** [comment]
Well, I have not reproduced the error.

**Comment by Shougo** [comment]
I think gin.vim implementation is changed, the error is not occurred.  Please test it again.

**Comment by lambdalisue** [comment]
![CleanShot 2022-04-01 at 09 57 44](https://user-images.githubusercontent.com/546312/161173988-dc098de8-ab69-4636-9e7f-d8641830b011.png)

That what I already mentioned 👍

**Comment by Shougo** [comment]
OK.  I have reproduced.  But it is bug of ddu.vim?
How to fix the problem??

**Comment by lambdalisue** [comment]
> OK. I have reproduced. But it is bug of ddu.vim?
How to fix the problem??

I've no idea as well. That why I mentioned that its more likely a bug on Vim/Neovim side.

> It seems sbuffer is called in statusline/tabline update context because of RPC asynchronous call and it seems that's not allowed. So I guess this is more likely a bug on Vim/Neovim side but not sure...

But I haven't faced similar issue on gin.vim even that gin.vim open buffers so maybe ddu has some code to cause this behavior? I don't know.

**Comment by Shougo** [comment]
> But I haven't faced similar issue on gin.vim even that gin.vim open buffers so maybe ddu has some code to cause this behavior? I don't know.

Ddu has asyncronous update.  It may be on statusline state?
