### ISSUE TITLE
Unexpected background color when cursor has moved with `ddu#ui#ff#execute()`

### ISSUE THREAD

**Issue by lambdalisue** [Shougo/ddu.vim#27]
**Warning: I will close the issue without the minimal init.vim and the
reproduction instructions.**

# Problems summary

Somehow unexpected background is applied to previous selected lines. When you hit `<C-o><C-l>`, the highlight is fixed.

https://user-images.githubusercontent.com/546312/188069762-56e751d6-478e-4a4e-b0d2-a573caac50cb.mp4

## Expected

Only current selected line is highlighted.

## Environment Information

- ddu.vim version (SHA1): 87653d73b09c91a5fbad714536506fa28e365b14

- denops.vim version (SHA1): 17030b4178076eefbde60f682a74a5b62b10c5e0

- deno version(`deno -V` output): 1.24.2

- OS: macOS 12.5.1 (Apple Sillicon)

- neovim/Vim `:version` output: NVIM v0.8.0-dev-2465-g12fe197cf-dirty

## Provide a minimal init.vim/vimrc without plugin managers (Required!)

```vim
if exists('+compatible') && &compatible
  set nocompatible
endif

" Disable Vim's native pack feature
set packpath=

" Clone https://github.com/lambdalisue/fern.vim in somewhere
" and specify that directory to the below
set runtimepath^=~/.config/nvim/pack/jetpack/src/github.com/vim-denops/denops.vim
set runtimepath^=~/.config/nvim/pack/jetpack/src/github.com/Shougo/ddu.vim
set runtimepath^=~/.config/nvim/pack/jetpack/src/github.com/Shougo/ddu-ui-ff
set runtimepath^=~/.config/nvim/pack/jetpack/src/github.com/Shougo/ddu-source-file_rec
set runtimepath^=~/.config/nvim/pack/jetpack/src/github.com/Shougo/ddu-filter-matcher_substring
set runtimepath^=~/.config/nvim/pack/jetpack/src/github.com/EdenEast/nightfox.nvim

filetype plugin indent on
syntax on
"----------------------------------------------------------------

nnoremap ; :
nnoremap : ;


call ddu#custom#patch_global({
      \ 'ui': 'ff',
      \ 'sources': [
      \   {
      \     'name': 'file_rec',
      \   },
      \ ],
      \ 'sourceOptions': {
      \   '_': {
      \     'matchers': ['matcher_substring'],
      \   },
      \ },
      \ 'uiParams': {
      \   'ff': {
      \     'split': 'floating',
      \     'startFilter': v:true,
      \     'prompt': '> ',
      \   },
      \ },
      \})

function! s:my_ddu_ff() abort
  nnoremap <buffer><silent> <Esc>
        \ <Cmd>call ddu#ui#ff#do_action('quit')<CR>
endfunction

function! s:my_ddu_ff_filter() abort
  inoremap <buffer><silent> <Esc> <Esc><Cmd>call ddu#ui#ff#close()<CR>
  nnoremap <buffer><silent> <Esc> <Cmd>call ddu#ui#ff#close()<CR>

  inoremap <buffer><silent> <C-n>
	  \ <Cmd>call ddu#ui#ff#execute("call cursor(line('.')+1,0)")<CR>
  inoremap <buffer><silent> <C-p>
	  \ <Cmd>call ddu#ui#ff#execute("call cursor(line('.')-1,0)")<CR>
endfunction

augroup my-ddu
  autocmd!
  autocmd FileType ddu-ff call s:my_ddu_ff()
  autocmd FileType ddu-ff-filter call s:my_ddu_ff_filter()
augroup END

colorscheme nightfox

"----------------------------------------------------------------
echomsg "Custom minimal vimrc has loaded"
```

## How to reproduce the problem from neovim/Vim startup (Required!)

1. `call ddu#start({})`
2. Hit `<C-n>` or `<C-p>`

**Comment by Shougo** [comment]
Hi.  I have tested it and it works as expected.

**Comment by Shougo** [comment]
I don't reproduce the problem with tmux.  Please test it in more bare environment.

**Comment by Shougo** [comment]
Reproduced.

**Comment by Shougo** [comment]
Fixed.  Please update `ddu-ui-ff`.

**Comment by lambdalisue** [comment]
It seems the change cause a new issue.

- Start up become slower somehow
- The cursor is forcedly moved to the first line randomly

https://user-images.githubusercontent.com/546312/188181785-d7cff692-1ccd-4cbf-81e9-c4c248c9c20e.mp4
