### ISSUE TITLE
`abbr` は `display` の方が妥当ではないか？

### ISSUE THREAD

**Issue by Bakudankun** [Shougo/ddu.vim#3]
こういうのどこに意見したら良いかわからないのでここに書きます。
`abbr` はabbreviation《略語》のことだと思うのですが、denite.nvimと同じように候補リスト上での表示テキストとして扱われる物なら、 `display` （または `displayText` ）などの方が適切だと思うのですが、どうでしょうか？
denite.nvimをカスタマイズしようとしたときに、 `abbr` の方が `word` よりも長かったりして（e.g. grep source）、 `word` と `abbr` のどちらが何なのか混乱したことがあるためです。
まだアルファの段階ということで、変えるなら今のうちかなと思い意見しました。

**Comment by Shougo** [comment]
それはそもそもドキュメント見てないのが悪いよね……

```
------------------------------------------------------------------------------
CANDIDATE ATTRIBUTES			*denite-candidate-attributes*

					*denite-candidate-attribute-name*
word		(String)			(Required)
		The word of a candidate. It is used for matching inputs.

					*denite-candidate-attribute-abbr*
abbr		(String)			(Optional)
		The string displayed in Denite buffer.  If it is omitted, word
		attribute is used instead.  It is not used for matching
		inputs.
```

`abbr` は Vim の補完由来の用語で私は分かりづらいと思ってなかったですが。

**Comment by Bakudankun** [comment]
ありがとうございます！
なるほど、Vimの補完由来だったんですね。（`:h complete-items`）
理解できましたが、dduの方は complete-items の `abbr` とは少し役割が違うと思うので、変えてもらえて良かったと思います！
