### ISSUE TITLE
The filter doesn't work.

### ISSUE THREAD

**Issue by nabezokodaikon** [Shougo/ddu.vim#4]
**Warning: I will close the issue without the minimal init.vim and the
reproduction instructions.**

# Problems summary
When set in Lua, the filter does not work.

## Expected
The filter works even when set in Lua.

## Environment Information

- ddu.vim version (SHA1):fc509869b5d41deee4a70383001c7d793a78a372

- denops.vim version (SHA1):333aa1783352c346cc4fbaa43217bbc1c07ddbaa

- deno version(`deno -V` output):1.18.1

- OS:Mac

- neovim/Vim `:version` output:v0.7.0-dev+956-g6cb670cb2

- `:checkhealth` or `:CheckHealth` result(neovim only):OK

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
if &compatible
    set nocompatible
endif
let $CACHE = expand('~/.cache')
if !isdirectory(expand($CACHE))
    call mkdir(expand($CACHE), 'p')
endif
let s:dein_dir = expand('$CACHE/dein')
let s:dein_repo_dir = s:dein_dir . '/repos/github.com/Shougo/dein.vim'
if &runtimepath !~# '/dein.vim'
    if !isdirectory(s:dein_repo_dir)
        execute '!git clone https://github.com/Shougo/dein.vim' s:dein_repo_dir
    endif
    execute 'set runtimepath^=' . s:dein_repo_dir
endif

call dein#begin(s:dein_dir, expand('<sfile>'))

call dein#add('vim-denops/denops.vim')
call dein#add('Shougo/ddu.vim')
call dein#add('Shougo/ddu-commands.vim')
call dein#add('Shougo/ddu-ui-std')
call dein#add('Shougo/ddu-filter-matcher_substring')
call dein#add('Shougo/ddu-source-file_rec')

call dein#end()
call dein#save_state()

lua << EOF
vim.call('ddu#custom#patch_global', 'ui', 'std')
vim.call('ddu#custom#patch_global', 'sourceOptions', '_', matchers, 'matcher_substring')
EOF

autocmd FileType ddu-std call s:ddu_my_settings()
function! s:ddu_my_settings() abort
        nnoremap <buffer><silent> <CR>
        \ <Cmd>call ddu#ui#std#do_map('doAction', {'name' : 'default'})<CR>
        nnoremap <buffer><silent> i
        \ <Cmd>call ddu#ui#std#do_map('openFilterWindow')<CR>
        nnoremap <buffer><silent> q
        \ <Cmd>call ddu#ui#std#do_map('quit')<CR>
endfunction

autocmd FileType ddu-std-filter call s:ddu_filter_my_settings()
function! s:ddu_filter_my_settings() abort
        inoremap <buffer><silent> <CR>
        \ <Esc><Cmd>close<CR>
        nnoremap <buffer><silent> <CR>
        \ <Cmd>close<CR>
endfunction
```

## How to reproduce the problem from neovim/Vim startup (Required!)

1. Run `call dein#update()` commnad.
2. Run `Ddu -name=search file_rec -ui-param-startFilter=v:true` command.

**Comment by nabezokodaikon** [comment]
I defined it as below and it worked.
`vim.call('ddu#custom#patch_global', 'sourceOptions', {_ = {matchers = {'matcher_substring'}}})`

**Comment by nabezokodaikon** [comment]
After defining multiple settings, it stopped working.
```vim
lua << EOF
vim.call('ddu#custom#patch_global',
        'ui', {'std'},
        'sourceOptions', {_ = {matchers = {'matcher_substring'}}}
        )
EOF
```

**Comment by Shougo** [comment]
You should know what you call the function.

`call ddu#custom#patch_global('ui', {'std'}, 'sourceOptions', { '_': { 'matchers': ['matcher_substring']})`

It does not work!!
Please read the documentation.

**Comment by Shougo** [comment]
```
						*ddu#custom#patch_global()*
ddu#custom#patch_global({option-name}, {value})
ddu#custom#patch_global({dict})
```

**Comment by nabezokodaikon** [comment]
Understand. Thank you for your reply.
