### ISSUE TITLE
ExpandItem is broken.

### ISSUE THREAD

**Issue by uga-rosa** [Shougo/ddu.vim#55]
**Warning: I will close the issue without the minimal init.vim and the
reproduction instructions.**

# Problems summary

Tree expansion does not work properly.

## Environment Information

All up-to-date. Updated just before making this issue.

- ddu.vim version (SHA1):

- denops.vim version (SHA1):

- deno version(`deno -V` output):

- OS:
Ubuntu 22.04 (WSL2)

- neovim/Vim `:version` output:
NVIM v0.10.0-dev-a0375b6

## Provide a minimal init.vim/vimrc without plugin managers (Required!)

Note that you need the [hierarchy branch of nvim_lsp source](https://github.com/uga-rosa/ddu-source-nvim_lsp/tree/hierarchy), not the main branch.

```vim
set runtimepath+=/path/to/denops.vim
set runtimepath+=/path/to/ddu.vim
set runtimepath+=/path/to/ddu-ui-ff
set runtimepath+=/path/to/ddu-source-nvim_lsp
set runtimepath+=/path/to/nvim-lspconfig

lua <<EOL
vim.fn["ddu#custom#patch_global"]({
  sources = {
    { name = "nvim_lsp", params = { method = "callHierarchy/incomingCalls" } }
  },
  ui = "ff",
  uiParams = {
    ff = {
      displayTree = true,
    },
  },
  kindOptions = {
    _ = {
      defaultAction = "open",
    },
  },
})

require("lspconfig").denols.setup({
  settings = {
    deno = true,
  },
})
EOL

augroup my-ddu-ff
  autocmd!
  autocmd FileType ddu-ff call <SID>ddu_ff_mapping()
augroup END

function! s:ddu_ff_mapping() abort
  nnoremap <buffer><silent> <CR> <Cmd>call ddu#ui#do_action('itemAction')<CR>
  nnoremap <buffer><silent> <Esc> <Cmd>call ddu#ui#do_action('quit')<CR>
  nnoremap <buffer><silent> e <Cmd>call ddu#ui#do_action('expandItem')<CR>
endfunction
```

## How to reproduce the problem from neovim/Vim startup (Required!)

Use nvim_lsp source code.

1. Open denops/@ddu-sources/nvim_lsp.ts and place the cursor on row 493, column 10 (on `callHierarchyHandler` symbol).
2. Run `:call ddu#start({})`.
3. Call expandItem with `e` on `callHierarchyHandler` symbol.
4. The `searchChildren` symbol will appear, so expandItem in the same way.
5. The `callHierarchyHandler` symbol disappears and the `searchChildren` symbol increases to two.

## Screenshot (if possible)

![expandItem](https://github.com/Shougo/ddu.vim/assets/82267684/26d7d3a3-1eba-4178-b367-111e2a611dc9)

**Comment by uga-rosa** [comment]
I found the cause: treePath is not defined.

**Comment by Shougo** [comment]
`treePath` must be set to support tree.
