### ISSUE TITLE
Cannot expand the tree from the beginning

### ISSUE THREAD

**Issue by uga-rosa** [Shougo/ddu.vim#56]
# Problems summary

I would like to expand items from the beginning, but it doesn't work.

## Expected
The tree structure is displayed correctly.

## Environment Information

- ddu.vim version (SHA1):
426c150ccc038ef76f5f7220d6fd6f066377672c

- denops.vim version (SHA1):
3b489d50ba2e034c829a09475a4002176bffbef7

- deno version(`deno -V` output):
deno 1.34.1

- OS:
Ubuntu 22.04 (WSL2)

- neovim/Vim `:version` output:
NVIM v0.10.0-dev-0370e4d

## Provide a minimal init.vim/vimrc without plugin managers (Required!)

```vim
set runtimepath+=/path/to/denops.vim
set runtimepath+=/path/to/ddu.vim
set runtimepath+=/path/to/ddu-ui-ff
set runtimepath+=/path/to/ddu-kind-file

call ddu#custom#patch_global(#{
      \ sources: [#{ name: 'expand' }],
      \ ui: 'ff',
      \ uiParams: #{
      \   ff: #{
      \     displayTree: v:true,
      \   },
      \ },
      \})

augroup my-ddu-ff
  autocmd!
  autocmd FileType ddu-ff call <SID>ddu_ff_mapping()
augroup END

function! s:ddu_ff_mapping() abort
  nnoremap <buffer><silent> <Esc> <Cmd>call ddu#ui#do_action('quit')<CR>
endfunction
```

And place this source under `stdpath('config')`.
- denops/@ddu-sources/expand.ts
```typescript
import { BaseSource, Item } from "https://deno.land/x/ddu_vim@v3.0.0/types.ts";
import { ActionData } from "https://deno.land/x/ddu_kind_file@v0.5.0/file.ts";

type Params = Record<never, never>;

export class Source extends BaseSource<Params> {
  kind = "file";

  gather(): ReadableStream<Item<ActionData>[]> {
    return new ReadableStream({
      start(controller) {
        controller.enqueue([
          {
            word: "foo",
            isTree: true,
            treePath: "/foo",
            isExpanded: true,
          },
          {
            word: "bar",
            isTree: false,
            treePath: "/foo/bar",
          },
        ]);
        controller.close();
      },
    });
  }

  params(): Params {
    return {};
  }
}
```

## How to reproduce the problem from neovim/Vim startup (Required!)

1. `call ddu#start({})`
2. You can already see that it's not a tree.

## Screenshot (if possible)
![image](https://github.com/Shougo/ddu.vim/assets/82267684/7c3cee10-b6e1-4a16-bb7e-2d42bd37d3d7)

**Comment by Shougo** [comment]
Fixed.  Please update `ddu-ui-ff`.

**Comment by uga-rosa** [comment]
Not fixed.
The `bar` is not a child of `foo`.

**Comment by uga-rosa** [comment]
I have confirmed the correction of the attribute-level. This issue has been resolved.
