### ISSUE TITLE
It is little inconvenient for not clearing input when  action narrow

### ISSUE THREAD

**Issue by kamecha** [Shougo/ddu.vim#62]
**Warning: I will close the issue without the minimal init.vim and the
reproduction instructions.**

# Problems summary
when the refreshItem action is fired, the input in filter window is not cleard.

## Expected
When it is, the input is cleared.

Or the behavior can be setting.

## Environment Information

- ddu.vim version (SHA1):
1f56014
- denops.vim version (SHA1):
62b1d22
- deno version(`deno -V` output):
deno 1.30.3
- OS:
WSL2 Ubuntu22.04

- neovim/Vim `:version` output:
NVIM v0.9.0-dev-1088+gd66832c76
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

## Provide a minimal init.vim/vimrc without plugin managers (Required!)

```vim
" Your minimal init.vim/vimrc
set rtp+=~/.cache/dein/nvim/repos/github.com/vim-denops/denops.vim
set rtp+=~/.cache/dein/nvim/repos/github.com/Shougo/ddu.vim
set rtp+=~/.cache/dein/nvim/repos/github.com/Shougo/ddu-ui-ff
set rtp+=~/.cache/dein/nvim/repos/github.com/Shougo/ddu-source-file
set rtp+=~/.cache/dein/nvim/repos/github.com/Shougo/ddu-kind-file

nnoremap [ddu] <Nop>
nmap <Space>u [ddu]
nmap <silent> [ddu]f <Cmd>call ddu#start({
			\ 'ui': 'ff',
			\ 'uiParams': {
			\	'ff': {
			\		'startFilter': v:true,
			\	}
			\ },
			\ 'sources': [
			\	{'name': 'file', 'params': {}},
			\ ],
			\ })<CR>

autocmd FileType ddu-ff call s:ddu_my_settings()

function! s:ddu_my_settings() abort
	setlocal cursorline
endfunction

autocmd FileType ddu-ff-filter call s:ddu_filter_my_settings()

function! s:ddu_filter_my_settings() abort
	inoremap <buffer> <CR>
				\ <ESC><Cmd>call ddu#ui#do_action('itemAction', {'name': 'narrow'})<CR>
	inoremap <buffer> <C-n>
				\ <Cmd>call ddu#ui#do_action("cursorNext")<CR>
	inoremap <buffer> <C-p>
				\ <Cmd>call ddu#ui#do_action("cursorPrevious")<CR>
endfunction

```

## How to reproduce the problem from neovim/Vim startup (Required!)
neovim/Vim should be started with a path that has a directory under it.

1. type `<Space>` `u` `f` for start ddu
2. input any char ( this input by itself doesn't make much sense for not setting any matcher )
3. select directory and type '<CR>'
4. the items in UI is refreshed, but the input in filter window is remained...

## Screenshot (if possible)
![ddu-refresh](https://github.com/Shougo/ddu.vim/assets/50443168/785b147f-abfc-4900-8729-b12d95038dce)

**Comment by Shougo** [comment]
Reproduced.  But it is not easy to fix.

**Comment by Shougo** [comment]
Fixed.
