### ISSUE TITLE
Tree expanded does not be kept by `resume`

### ISSUE THREAD

**Issue by ryota2357** [Shougo/ddu.vim#63]
# Problems summary

ddu does not keep the previous tree expanded even if I set `resume` to true.

This behavior occurs from 7fef2fbc66e0b643b3ce5b7e3d487efd0c992052

## Expected

Keep the tree expanded.

## Environment Information

- ddu.vim version (SHA1): 3202e53453d082cce9e829048d2c285864d5ceab

- denops.vim version (SHA1): 62b1d22b3e60fcc9e570a531a5af1e4b2393c15a

- deno version(`deno -V` output): deno 1.34.3

- OS: MacOS

- neovim/Vim `:version` output:

```
NVIM v0.10.0-dev-1973+g54807231c-Homebrew
Build type: Release
LuaJIT 2.1.0-beta3
Run ":verbose version" for more info
```

## Provide a minimal init.vim/vimrc without plugin managers (Required!)

```vim
if !has("nvim")
  set nocompatible
  filetype plugin indent on
  syntax enable
endif

let s:plugins = [
      \ 'vim-denops/denops.vim',
      \ 'Shougo/ddu.vim',
      \ 'Shougo/ddu-ui-filer',
      \ 'ryota2357/ddu-column-icon_filename',
      \ 'Shougo/ddu-source-file',
      \ 'Shougo/ddu-kind-file',
      \ ]
for item in s:plugins
  execute 'set runtimepath+=~/.cache/dein/repos/github.com/' .. item
endfor

call ddu#custom#patch_global(#{
    \   ui: 'filer',
    \   sources: [{'name': 'file'}],
    \   resume: v:true,
    \   sourceOptions: {
    \     '_': { 'columns': ['icon_filename'] }
    \   },
    \   kindOptions: #{
    \     file: #{
    \       defaultAction: 'open',
    \     },
    \   }
    \ })

autocmd FileType ddu-filer call s:ddu_my_settings()
function! s:ddu_my_settings() abort
  nnoremap <buffer><expr> <CR> ddu#ui#get_item()->get('isTree', v:false)
    \ ? "<Cmd>call ddu#ui#filer#do_action('expandItem', {'mode': 'toggle'})<CR>"
    \ : "<Cmd>call ddu#ui#filer#do_action('itemAction')<CR>"
  nnoremap <buffer> q <Cmd>call ddu#ui#filer#do_action('quit')<CR>
endfunction
```

## How to reproduce the problem from neovim/Vim startup (Required!)

1. start neovim
2. `call ddu#start()`.
3. `<CR>` on the directory to expand the tree.
4. `q` to quit.
5. `call ddu#start()` to restart.

## Screenshot (if possible)

https://github.com/Shougo/ddu.vim/assets/61523777/343d8d53-52ce-4e44-be03-ab6e8a59a116

**Comment by Shougo** [comment]
Fixed.  Please update `ddu.vim`.
