### ISSUE TITLE
ddu.vim cannot show multiple columns

### ISSUE THREAD

**Issue by kyoh86** [Shougo/ddu.vim#67]
# Problems summary

Using multiple columns, but I can see only one last column.

## Expected

Multiple columns are shown.

After the minimal init.vim and setup script below run, I expect `TestStart()` shows slug (filename without ext) and title (from frontmatter) like:
```
foo bar
```

## Environment Information

- ddu.vim version (SHA1): `11c81d8a4f3f05f88f1254b3086557a3a1041fab`

- denops.vim version (SHA1): `62b1d22b3e60fcc9e570a531a5af1e4b2393c15a`

- deno version(`deno -V` output): `deno 1.34.3`

- OS: Arch Linux in WSL2

- neovim/Vim `:version` output:

```
NVIM v0.10.0-dev-2afb047
Build type: Release
LuaJIT 2.1.0-beta3
Run ":verbose version" for more info
```

## Provide a minimal init.vim/vimrc without plugin managers (Required!)

```vim
set rtp+=~/test_ddu_vim_64/plug/denops.vim
set rtp+=~/test_ddu_vim_64/plug/ddu.vim
set rtp+=~/test_ddu_vim_64/plug/ddu-ui-ff
set rtp+=~/test_ddu_vim_64/plug/ddu-kind-file
set rtp+=~/test_ddu_vim_64/plug/ddu-source-zenn_dev

function! TestStart()
  call ddu#start(#{
    \   name: "ddu-zenn_dev",
    \   sources: [ #{ name: "zenn_dev_article" } ],
    \   sourceOptions: #{ _: #{ path: expand("~/test_ddu_vim_64"), columns: [ "zenn_dev_slug", "zenn_dev_title" ] } },
    \   ui: "ff",
    \ })
endfunction
```

**And it depends on some files & plugins**

```sh
mkdir -p ~/test_ddu_vim_64/articles

echo '---'           > ~/test_ddu_vim_64/articles/foo.md
echo 'title: "bar"' >> ~/test_ddu_vim_64/articles/foo.md
echo 'emoji: "🐼"'  >> ~/test_ddu_vim_64/articles/foo.md
echo '---'          >> ~/test_ddu_vim_64/articles/foo.md

git clone https://github.com/vim-denops/denops.vim      ~/test_ddu_vim_64/plug/denops.vim
git clone https://github.com/Shougo/ddu.vim             ~/test_ddu_vim_64/plug/ddu.vim
git clone https://github.com/Shougo/ddu-ui-ff           ~/test_ddu_vim_64/plug/ddu-ui-ff
git clone https://github.com/Shougo/ddu-kind-file       ~/test_ddu_vim_64/plug/ddu-kind-file
git clone https://github.com/kyoh86/ddu-source-zenn_dev ~/test_ddu_vim_64/plug/ddu-source-zenn_dev
```

## How to reproduce the problem from neovim/Vim startup (Required!)

1. `:call TestStart()`

## Screenshot (if possible)

![image](https://github.com/Shougo/ddu.vim/assets/5582459/d0059298-7624-4ae3-afe0-b85473c80874)

**Comment by Shougo** [comment]
Fixed.
