### ISSUE TITLE
`expandItem` does not work well with not directory item

### ISSUE THREAD

**Issue by kamecha** [Shougo/ddu.vim#70]
**Warning: I will close the issue without the minimal init.vim and the
reproduction instructions.**

# Problems summary
SSIA

## Expected
When `expandItem` fired with not directory item, `expandItem` action doesn't do anything.

## Environment Information

- ddu.vim version (SHA1):
bc0cc74
- denops.vim version (SHA1):
05de850
- deno version(`deno -V` output):
deno 1.30.3
- OS:
WSL2 Ubuntu22.04
- neovim/Vim `:version` output:
NVIM v0.9.0-dev-1088+gd66832c76
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

## Provide a minimal init.vim/vimrc without plugin managers (Required!)

```vim
set rtp+=~/.cache/dein/nvim/repos/github.com/vim-denops/denops.vim
set rtp+=~/.cache/dein/nvim/repos/github.com/Shougo/ddu.vim
set rtp+=~/.cache/dein/nvim/repos/github.com/Shougo/ddu-ui-ff
set rtp+=~/.cache/dein/nvim/repos/github.com/Shougo/ddu-source-file
set rtp+=~/.cache/dein/nvim/repos/github.com/Shougo/ddu-kind-file

nnoremap [ddu] <Nop>
nmap <Space>u [ddu]
nmap <silent> [ddu]f <Cmd>call ddu#start({
			\ 'ui': 'ff',
			\ 'sources': [
			\	{'name': 'file', 'params': {}},
			\ ],
			\ })<CR>
autocmd FileType ddu-ff call s:ddu_my_settings()

function! s:ddu_my_settings() abort
	nnoremap <buffer> e
				\ <Cmd>call ddu#ui#do_action('expandItem', {'mode': 'toggle'})<CR>
endfunction

```

## How to reproduce the problem from neovim/Vim startup (Required!)

1. type `<Space>` `u` `f` for start ddu
2. type `e` when the cursor is on the file, not directory.
3. the item is expanded even though it is not directory.

## Screenshot (if possible)
type `e` when the cursor is on `min.vim` (not directory) ...

![image](https://github.com/Shougo/ddu.vim/assets/50443168/e4e755d3-c8db-468e-a8b0-14072d36f679)

**Comment by Shougo** [comment]
I will look it later.

**Comment by Shougo** [comment]
Fixed.
