### ISSUE TITLE
Filter ordering changed?

### ISSUE THREAD

**Issue by dmfay** [Shougo/ddu.vim#85]
# Problems summary

I upgraded recently and noticed a behavior change with grep. I had configured converter_display_word and [ddu-filter-fzf](https://github.com/yuki-yano/ddu-filter-fzf) in order to filter on both the filename and the matched line. Now only the matched line is filtered.

I found a [commit](https://github.com/Shougo/ddu.vim/commit/ef28c91caad462765c77ae573e9a23fe6622ed0d) newly specifying that filters are applied matcher -> sorter -> converter, and adding logs in converter_display_word and ddu-filter-fzf confirmed this. filter-fzf logged first, then converter_display_word. So both the `matcherKey` and `word` for fzf only contain the matched line instead of "$filename: $matchedLine". How can I filter on both?

## Environment Information

- ddu.vim version (SHA1): 67736ddea282bd8941097600e0d1af4ff6f4b8a1
- denops.vim version (SHA1): 8b53173370d3c2285abb34569b8d00b73d06eaa3
- deno version(`deno -V` output): `deno 1.37.2`
- OS: Arch Linux, also happened on macOS
- neovim/Vim `:version` output:
```
NVIM v0.9.4
Build type: Release
LuaJIT 2.1.1697887905
```

## Provide a minimal init.vim/vimrc without plugin managers (Required!)

```vim
if has('vim_starting')
  let s:config_path = stdpath('cache')
  for s:repo in [
    \ 'vim-denops/denops.vim',
    \ 'Shougo/ddu.vim',
    \ 'Shougo/ddu-ui-ff',
    \ 'Shougo/ddu-kind-file',
    \ 'shun/ddu-source-rg',
    \ 'Shougo/ddu-filter-converter_display_word',
    \ 'yuki-yano/ddu-filter-fzf'
  \ ]
    let s:path = s:config_path . '/../dein/repos/github.com/' . s:repo
    let &g:rtp .= ',' . s:path
  endfor
endif

call ddu#custom#patch_global(#{
  \   ui: 'ff',
  \   uiParams: #{
  \     ff: #{
  \       startFilter: v:true,
  \       ignoreEmpty: v:false,
  \       autoResize: v:false,
  \       filterSplitDirection: 'botright',
  \       cursorPos: 0,
  \     }
  \   },
  \   kindOptions: #{
  \     file: #{
  \       defaultAction: 'open',
  \     },
  \   },
  \   filterParams: #{
  \     matcher_fzf: #{
  \       highlightMatched: 'Search',
  \     },
  \   },
  \   sources: [
  \     #{ name: 'rg', },
  \   ],
  \   sourceOptions: #{
  \     _: #{
  \       converters: [
  \         'converter_display_word',
  \       ],
  \       sorters: ['sorter_fzf'],
  \       matchers: ['matcher_fzf'],
  \     },
  \   },
  \   sourceParams: #{
  \     rg: #{
  \       args: ['--column', '--no-heading', '--smart-case', '--color', 'never'],
  \       highlights: #{path: 'Url'},
  \     },
  \   },
  \ })

autocmd FileType ddu-ff-filter call s:ddu_filter_my_settings()
function! s:ddu_filter_my_settings() abort
  inoremap <buffer> <CR>
    \ <Esc><Cmd>call ddu#ui#ff#do_action('itemAction')<CR>
  inoremap <buffer> <Esc>
    \ <Esc><Cmd>call ddu#ui#ff#do_action('quit')<CR>
  inoremap <buffer> <C-j>
    \ <Cmd>call ddu#ui#ff#execute(
    \ "call cursor(line('.')+1,0)<Bar>redraw")<CR>
  inoremap <buffer> <C-k>
    \ <Cmd>call ddu#ui#ff#execute(
    \ "call cursor(line('.')-1,0)<Bar>redraw")<CR>
endfunction

nnoremap <space>/
  \ :call ddu#start(#{
  \   sources: [#{name: 'rg', params: #{input: input('pattern-')}}],
  \ })<CR>
```

## How to reproduce the problem from neovim/Vim startup (Required!)

1. `<space>/` to open grep prompt
2. type search string and press enter
3. try to filter results by filename; you will only match characters in the grep output

## Screenshot (if possible)

![1700668636](https://github.com/Shougo/ddu.vim/assets/3075455/5f815a16-cb51-453d-aeee-e1612078861f)

Before I upgraded, this fzf filter string `types` would have matched all results in types.ts first since that's the earliest matching text in `$filename $matchedLine`.

**Comment by Shougo** [comment]
Your configuration is wrong.  The filter order is not changed.

If you want to change match, you need to change `matchers` like this.
`converter_display_word` must be executed before `matcher_fzf`.

```vim
  \   sourceOptions: #{
  \     _: #{
  \       converters: [],
  \       sorters: [ 'sorter_fzf'],
  \       matchers: [converter_display_word','matcher_fzf'],
  \     },
  \   },
```

**Comment by dmfay** [comment]
I didn't realize the filters could go anywhere in the pipeline, thank you!

**Comment by Shougo** [comment]
All filters has same interface.

`matcher`, `sorter`, `converter` is just applied order.
