### ISSUE TITLE
mismatched highlight in ddu-column

### ISSUE THREAD

**Issue by kamecha** [Shougo/ddu.vim#91]
**Warning: I will close the issue without the minimal init.vim and the
reproduction instructions.**

# Problems summary
highlights set by the each column plugin does not work well.

## Expected
each highlights is set correctly.

## Environment Information

- ddu.vim version (SHA1):
1b098b9
- denops.vim version (SHA1):
886bfa0
- deno version(`deno -V` output):
deno 1.38.0
- OS:
WSL2 Ubuntu22.04.3 LTS
- neovim/Vim `:version` output:
NVIM v0.10.0-dev-1846+gf31f260f0
Build type: RelWithDebInfo
LuaJIT 2.1.1702233742
Run ":verbose version" for more info

## Provide a minimal init.vim/vimrc without plugin managers (Required!)
Firstly, you have to clone this repository and install nerdfont. this repository is created for testing ddu-column.

https://github.com/kamecha/ddu-column-test

and write vimrc like bellow. ( the vimrc is included in ddu-column-test as min.vim)

```vim
" Your minimal init.vim/vimrc
set rtp+=~/.cache/dein/nvim/repos/github.com/vim-denops/denops.vim

" ddu
set rtp+=~/.cache/dein/nvim/repos/github.com/Shougo/ddu.vim
set rtp+=~/.cache/dein/nvim/repos/github.com/Shougo/ddu-ui-ff

set rtp+=~/workspace/Plugin/ddu-column-test

filetype plugin indent on

" setting for ddu
let s:ddu_setting_json =<< trim END
{
	"ui": "ff",
	"sources": ["otameshi"],
	"sourceOptions": {
		"_": {
			"columns": ["icon", "icon"]
		}
	}
}
END

call ddu#custom#patch_global(s:ddu_setting_json->join('')->json_decode())

nnoremap <silent> <Leader>d <Cmd>call ddu#start()<CR>

" filetype(ddu-ff) setting

autocmd FileType ddu-ff call s:ddu_ff_setting()

function s:ddu_ff_setting()
	nnoremap <buffer><silent> q
				\	<Cmd>call ddu#ui#do_action('quit')<CR>
	nnoremap <buffer><silent> e
				\	<Cmd>call ddu#ui#ff#do_action('expandItem', #{ mode: "toggle" })<CR>
endfunction
```

## How to reproduce the problem from neovim/Vim startup (Required!)

1. start vim
2. type `\` `d` for start ddu. (`\` or specified `<Leader>` key)
3. in ddu window, highlight is sed incorrectly

## Screenshot (if possible)
![image](https://github.com/Shougo/ddu.vim/assets/50443168/6f4a8356-f16c-4e8f-9ff7-f3358fb81c34)

**Comment by kamecha** [comment]
I think the white space between each column should be none.

**Comment by Shougo** [comment]
> I think the white space between each column should be none.

No.  It is feature.

**Comment by Shougo** [comment]
OK.  Reproduced.  You must use `strlen()` instead of `strdisplaywidth()`.
Because Vim/neovim highlight is length instead of width!

**Comment by kamecha** [comment]
sorry
I didn't understand the specifications of the highlight.
From now on I will use `strlen()`.

**Comment by kamecha** [comment]
using `strlen()` the column viewed like bellow.
![image](https://github.com/Shougo/ddu.vim/assets/50443168/08264b9e-f5f0-4fab-917f-08cfe053d83f)

the highlight is correctly set.
Thankyou! 👍

**Comment by Shougo** [comment]
I have updated the documentation.
`width` may be confused.  Sorry.

And I have added the padding for it.
