### ISSUE TITLE
columns set via source-options have uncorrect params.

### ISSUE THREAD

**Issue by kamecha** [Shougo/ddu.vim#92]
**Warning: I will close the issue without the minimal init.vim and the
reproduction instructions.**

# Problems summary
columns set like bellow does not work well.
```vim
#{
  columns: [
    #{ name: "test", params: #{ hoge: "piyo" } }
    #{ name: "test", params: #{ hoge: "poyo" } }
  ]
}
```

## Expected
each columns which has same `name` but has different `params` or `options`, work correctly.

## Environment Information

- ddu.vim version (SHA1):
5de9271
- denops.vim version (SHA1):
886bfa0
- deno version(`deno -V` output):
deno 1.38.0
- OS:
WSL2 ubuntu22.04
- neovim/Vim `:version` output:
NVIM v0.10.0-dev-1846+gf31f260f0
Build type: RelWithDebInfo
LuaJIT 2.1.1702233742
Run ":verbose version" for more info

## Provide a minimal init.vim/vimrc without plugin managers (Required!)
firstly you should install repository bellow  
https://github.com/kamecha/ddu-column-test

```vim
" Your minimal init.vim/vimrc
set rtp+=~/.cache/dein/nvim/repos/github.com/vim-denops/denops.vim

" ddu
set rtp+=~/.cache/dein/nvim/repos/github.com/Shougo/ddu.vim
set rtp+=~/.cache/dein/nvim/repos/github.com/Shougo/ddu-ui-ff

set rtp+=~/workspace/Plugin/ddu-column-test

filetype plugin indent on

" setting for ddu
let s:ddu_setting_json =<< trim END
{
	"ui": "ff",
	"sources": ["otameshi"],
	"sourceOptions": {
		"_": {
			"columns": [
				{ "name": "param", "params": { "text": " unko" } },
				{ "name": "param", "params": { "text": " test" } }
			]
		}
	}
}
END

call ddu#custom#patch_global(s:ddu_setting_json->join('')->json_decode())

nnoremap <silent> <Leader>d <Cmd>call ddu#start()<CR>

```

## How to reproduce the problem from neovim/Vim startup (Required!)

1. type `\` `d` to start ddu
2. in ui window, the `unko` does not displayed

## Screenshot (if possible)
![image](https://github.com/Shougo/ddu.vim/assets/50443168/087ae4a1-7f72-4d2a-b500-fd7c202a8854)

## Note
If I use `ddu#custom#alias` like bellow, it can be displayed correctly.
```vim
" Your minimal init.vim/vimrc
set rtp+=~/.cache/dein/nvim/repos/github.com/vim-denops/denops.vim

" ddu
set rtp+=~/.cache/dein/nvim/repos/github.com/Shougo/ddu.vim
set rtp+=~/.cache/dein/nvim/repos/github.com/Shougo/ddu-ui-ff

set rtp+=~/workspace/Plugin/ddu-column-test

filetype plugin indent on

call ddu#custom#alias('column', 'param1', 'param')

" setting for ddu
let s:ddu_setting_json =<< trim END
{
	"ui": "ff",
	"sources": ["otameshi"],
	"sourceOptions": {
		"_": {
			"columns": [
				{ "name": "param", "params": { "text": " unko" } },
				{ "name": "param1", "params": { "text": " test" } }
			]
		}
	}
}
END

call ddu#custom#patch_global(s:ddu_setting_json->join('')->json_decode())

nnoremap <silent> <Leader>d <Cmd>call ddu#start()<CR>

```

**Comment by kamecha** [comment]
Is this feature?

**Comment by Shougo** [comment]
The param seems cached....

**Comment by Shougo** [comment]
Fixed.
