### ISSUE TITLE
filters for parent item in `expandItem` and `collapseItem` is not working when use filters and columns.

### ISSUE THREAD

**Issue by kamecha** [Shougo/ddu.vim#98]
**Warning: I will close the issue without the minimal init.vim and the
reproduction instructions.**

# Problems summary
SSIA

## Expected
filters is applied for parent item even after `expandItem` and `collapseItem` when use filters and columns.

## Environment Information

- ddu.vim version (SHA1):
f754dbf

- denops.vim version (SHA1):
6489b17

- deno version(`deno -V` output):
deno 1.38.5

- OS:
WSL2 Ubuntu 22.04.3

- neovim/Vim `:version` output:
NVIM v0.10.0-dev-1846+gf31f260f0
Build type: RelWithDebInfo
LuaJIT 2.1.1702233742

## Provide a minimal init.vim/vimrc without plugin managers (Required!)

```vim
set rtp+=~/.cache/dein/nvim/repos/github.com/vim-denops/denops.vim

set rtp+=~/.cache/dein/nvim/repos/github.com/Shougo/ddu.vim
set rtp+=~/.cache/dein/nvim/repos/github.com/Shougo/ddu-ui-ff
set rtp+=~/.cache/dein/nvim/repos/github.com/Shougo/ddu-source-file
set rtp+=~/.cache/dein/nvim/repos/github.com/Shougo/ddu-kind-file
set rtp+=~/.cache/dein/nvim/repos/github.com/kamecha/ddu-filter-converter_file_info
set rtp+=~/.cache/dein/nvim/repos/github.com/Shougo/ddu-column-filename

nnoremap [ddu] <Nop>
nmap <Space>u [ddu]
nmap <silent> [ddu]F <Cmd>call ddu#start(#{
			\ ui: 'ff',
			\ sources: [#{name: 'file', options: #{
			\   columns: [#{name: 'filename'}],
			\   converters: [#{name: 'converter_file_info'}],
			\ }}],
			\ })<CR>

autocmd FileType ddu-ff call s:ddu_my_settings()

function! s:ddu_my_settings() abort
	nnoremap <buffer> e
				\ <Cmd>call ddu#ui#do_action('expandItem', {'mode': 'toggle'})<CR>
	nnoremap <buffer><silent> q
				\ <Cmd>call ddu#ui#do_action('quit')<CR>
endfunction

```

## How to reproduce the problem from neovim/Vim startup (Required!)

1. type `<Space>` `u` `F` to start ddu
2. type `e` on directory item to fire `expandItem` action
3. the parent item's display is not applied converters

## Screenshot (if possible)
![hoge](https://github.com/Shougo/ddu.vim/assets/50443168/c414c56b-788f-4db7-8d26-cb4d9598857a)

## Note
when I don't use columns and fire `expandItem`, the display is applied converter.

**Comment by Shougo** [comment]
Fixed.
