### ISSUE TITLE
highlight on column is shifted? when fire `expandItem` or `collapseItem`

### ISSUE THREAD

**Issue by kamecha** [Shougo/ddu.vim#99]
**Warning: I will close the issue without the minimal init.vim and the
reproduction instructions.**

# Problems summary
SSIA

## Expected
each highlight is correctly setted.

## Environment Information

- ddu.vim version (SHA1):
71c0fdf

- denops.vim version (SHA1):
16d4bbc

- deno version(`deno -V` output):
deno 1.40.1

- OS:
macOS 13.6.3 22G436 x86_64 

- neovim/Vim `:version` output:
NVIM v0.10.0-dev-1492+g3ca967387-Homebrew
Build type: Release
LuaJIT 2.1.1699180677

## Provide a minimal init.vim/vimrc without plugin managers (Required!)

```vim
set rtp+=~/.cache/dein/nvim/repos/github.com/vim-denops/denops.vim

" ddu
set rtp+=~/.cache/dein/nvim/repos/github.com/Shougo/ddu.vim
set rtp+=~/.cache/dein/nvim/repos/github.com/Shougo/ddu-ui-ff
set rtp+=~/.cache/dein/nvim/repos/github.com/Shougo/ddu-source-file
set rtp+=~/.cache/dein/nvim/repos/github.com/Shougo/ddu-column-filename

" you must install https://github.com/kamecha/ddu-column-test
set rtp+=~/workspace/Plugin/ddu-column-test
filetype plugin indent on

" setting for ddu
let s:ddu_setting_json =<< trim END
{
	"ui": "ff",
	"sources": [
		"file"
	],
	"sourceOptions": {
		"_": {
			"columns": [
				"filename",
				{
					"name": "param",
					"params": {
						"text": "unko",
						"highlights": [
							{
								"name": "ddu-column-param",
								"hl_group": "ErrorMsg",
								"width": 1
							}
						]
					}
				}
			]
		}
	}
}
END

call ddu#custom#patch_global(s:ddu_setting_json->join('')->json_decode())

nnoremap <silent> <Leader>d <Cmd>call ddu#start()<CR>

" filetype(ddu-ff) setting

autocmd FileType ddu-ff call s:ddu_ff_setting()

function s:ddu_ff_setting()
	nnoremap <buffer><silent> q
				\	<Cmd>call ddu#ui#do_action('quit')<CR>
	nnoremap <buffer><silent> e
				\	<Cmd>call ddu#ui#do_action('expandItem', #{ mode: "toggle" })<CR>
endfunction

```

## How to reproduce the problem from neovim/Vim startup (Required!)
you must install [ddu-column-test](https://github.com/kamecha/ddu-column-test) for ddu-column-param.

1. type `<Leader>` `d` to start ddu
2. type `e` on directory item
3. type `e` on the item which are same before item

## Screenshot (if possible)
<img width="637" alt="スクリーンショット 2024-01-27 16 03 01" src="https://github.com/Shougo/ddu.vim/assets/50443168/bc45345c-2736-43cc-b782-b94e0edf313d">

## Notes
ddu-column-param 's highlight's col is always `startCol`.

**Comment by Shougo** [comment]
I don't reproduce the error.  I think it depends on window width and directory.

**Comment by kamecha** [comment]
<img width="186" alt="スクリーンショット 2024-01-28 13 01 15" src="https://github.com/Shougo/ddu.vim/assets/50443168/74dd6117-d373-44ca-835c-4e8913eb98f2">

sorry, there was a lack of information. it maybe reproduce if directory tree is above.

To make the tree, you should add the code bellow to init.vim/.vimrc
```vim
" make directory
call mkdir($PWD .. '/test/aa/aaaa', 'p')
call writefile([], $PWD .. '/test/bb')
cd test
echomsg "please delete test directory after close vim"
```

<details>
<summary>all init.vim/.vimrc</summary>

```vim
set rtp+=~/.cache/dein/nvim/repos/github.com/vim-denops/denops.vim

" ddu
set rtp+=~/.cache/dein/nvim/repos/github.com/Shougo/ddu.vim
set rtp+=~/.cache/dein/nvim/repos/github.com/Shougo/ddu-ui-ff
set rtp+=~/.cache/dein/nvim/repos/github.com/Shougo/ddu-source-file
set rtp+=~/.cache/dein/nvim/repos/github.com/Shougo/ddu-column-filename

" you must install https://github.com/kamecha/ddu-column-test
set rtp+=~/workspace/Plugin/ddu-column-test
filetype plugin indent on

" setting for ddu
let s:ddu_setting_json =<< trim END
{
	"ui": "ff",
	"sources": [
		"file"
	],
	"sourceOptions": {
		"_": {
			"columns": [
				"filename",
				{
					"name": "param",
					"params": {
						"text": "unko",
						"highlights": [
							{
								"name": "ddu-column-param",
								"hl_group": "ErrorMsg",
								"width": 1
							}
						]
					}
				}
			]
		}
	}
}
END

call ddu#custom#patch_global(s:ddu_setting_json->join('')->json_decode())

nnoremap <silent> <Leader>d <Cmd>call ddu#start()<CR>

" filetype(ddu-ff) setting

autocmd FileType ddu-ff call s:ddu_ff_setting()

function s:ddu_ff_setting()
	nnoremap <buffer><silent> q
				\	<Cmd>call ddu#ui#do_action('quit')<CR>
	nnoremap <buffer><silent> e
				\	<Cmd>call ddu#ui#do_action('expandItem', #{ mode: "toggle" })<CR>
endfunction

" ======== add bellow code to make tree ============
call mkdir($PWD .. '/test/aa/aaaa', 'p')
call writefile([], $PWD .. '/test/bb')
cd test
echomsg "please delete test directory after close vim"
```
</details>

1. type `<Leader>` `d` to start ddu
1. type `e` on the directory aa to fire `expandItem` action
    - in this action, the display is correct
1. type `e` on the directory aaaa to fire `expandItem` action
    - in this action, the display is **not** correct
1. type `e` on the directory aaaa to collapse Item via `expandItem` action
    - in this action, the display is **not** correct

<img width="186" alt="スクリーンショット 2024-01-28 13 13 13" src="https://github.com/Shougo/ddu.vim/assets/50443168/6a347f26-3a95-4e7f-b11a-b47df8086349">

**Comment by Shougo** [comment]
Fixed.
